apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xiri
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xiri
    app.kubernetes.io/part-of: ci1t-830-0099-app
  name: devfile-sample-xiri
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xiri
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xiri
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0099-tenant/ci1t-830-0099-app/devfile-sample-xiri@sha256:b535245599451c32c5eb7c053fe97922d5edbd849d16197029a22ae7ce1d4de1
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
